<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lakkalikoori</name>
   <tag></tag>
   <elementGuidId>2fd73afc-da6b-4c93-be87-80f7934bbac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='shopping_seasoning_products']/tbody/tr[7]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>524c94b9-f789-4914-bdca-37a50baf35e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://training.openspan.com/product/detail/1/76</value>
      <webElementGuid>0bf73d14-b0bf-49e6-84f6-798529496417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product_detail_text</value>
      <webElementGuid>db1394e6-b73b-4987-ae8a-fa8217221466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lakkalikoori</value>
      <webElementGuid>7621049a-7bcb-4bec-95ec-2875ef72a612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping_seasoning_products&quot;)/tbody[1]/tr[7]/td[@class=&quot;product&quot;]/a[@class=&quot;product_detail_text&quot;]</value>
      <webElementGuid>ee8da4de-cb6f-4877-88f3-dacac7bbb7ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping_seasoning_products']/tbody/tr[7]/td/a</value>
      <webElementGuid>3512c02a-9aad-4783-bf9e-d8e19670aef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lakkalikoori')]</value>
      <webElementGuid>8a231eaf-f95a-4e27-8171-6539341639e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ipoh Coffee'])[1]/following::a[1]</value>
      <webElementGuid>c0f7726f-67d2-482b-b73d-c3b28cee95f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guarana Fantastica'])[1]/following::a[2]</value>
      <webElementGuid>20159279-1ea8-49b0-a1d4-d07f89930c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laughing Lumberjack Lager'])[1]/preceding::a[1]</value>
      <webElementGuid>2a776c58-7e40-416b-bf89-731ba97acbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outback Lager'])[1]/preceding::a[2]</value>
      <webElementGuid>fbff4cb5-8427-4019-978c-9258d8895de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lakkalikoori']/parent::*</value>
      <webElementGuid>3652ed57-637a-4e34-810c-9a110b5b4239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://training.openspan.com/product/detail/1/76')]</value>
      <webElementGuid>97fc2bc0-79a1-432d-b564-1e1b39ea87e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/a</value>
      <webElementGuid>843461b0-cb3b-41c7-afed-1ba2aff06483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://training.openspan.com/product/detail/1/76' and (text() = 'Lakkalikoori' or . = 'Lakkalikoori')]</value>
      <webElementGuid>ed1ec03d-dfc9-4320-84ba-02b87e83d3f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
