<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_11.25_continue_shopping</name>
   <tag></tag>
   <elementGuidId>a5f60b42-1be6-499c-b533-ef213f9e6f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ab91da5-9c18-4dea-ad04-e6881a9cb801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6e7a3cd-3b4d-4c09-ac99-7b6c8d0439b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_button</value>
      <webElementGuid>92aa52e9-22b6-4bb1-ab7d-ff995f230c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continue_shopping</value>
      <webElementGuid>f8784ce1-8a07-488c-ae28-d64ee710c3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue Shopping</value>
      <webElementGuid>28b1d1c0-5fcd-48cf-92ed-cee3759617da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='https://training.openspan.com/products'</value>
      <webElementGuid>6e2e90bc-e8d4-4d41-a352-453fbe48266d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box_border&quot;)/p[2]/input[@id=&quot;login_button&quot;]</value>
      <webElementGuid>28a2306a-29aa-4961-912a-50755775cbb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_button']</value>
      <webElementGuid>dfb2a666-0ccd-4cff-89d4-09e48a9a502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box_border']/p[2]/input</value>
      <webElementGuid>913292f9-bb54-4101-93e4-05b9a07e988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ad03396b-8e3f-40a9-86f5-db587ede7e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'login_button' and @name = 'continue_shopping']</value>
      <webElementGuid>213058be-6990-4bc0-bcb8-725dabca41be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
