<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beverages</name>
   <tag></tag>
   <elementGuidId>5f81a873-21d4-47db-a17c-e229c8fbab22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='my-beverages-table']/tbody/tr[2]/th/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>faf7c84c-38d0-4010-96f7-f5d416ce07d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://training.openspan.com/product/beverages</value>
      <webElementGuid>d85f6cfb-5f82-4616-b466-2a7a16f6e9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beverages</value>
      <webElementGuid>9478990a-dd90-468c-9071-71975a8cc4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-beverages-table&quot;)/tbody[1]/tr[2]/th[1]/a[1]</value>
      <webElementGuid>e0767d8b-f123-4c3c-b52b-24e95dd1a195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='my-beverages-table']/tbody/tr[2]/th/a</value>
      <webElementGuid>3f87648d-7937-4688-b971-ef1c7f9dabf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Beverages')])[2]</value>
      <webElementGuid>7529be9d-92e8-4d3a-81de-39bf693b5e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>18843d77-e17d-4ee8-9867-b4b7c84ce790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/following::a[3]</value>
      <webElementGuid>b5056db4-6c19-4155-a47b-1eb76e78f131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seasonings'])[2]/preceding::a[2]</value>
      <webElementGuid>b8449a01-2ef8-45e8-a387-7a389756cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[3]</value>
      <webElementGuid>5dc5f84c-247b-4a75-b2a5-74a958bf04b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://training.openspan.com/product/beverages')])[3]</value>
      <webElementGuid>bdb9db03-7f60-49e9-8c90-206d54e2f301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a</value>
      <webElementGuid>360fbfe1-900d-48ab-bdf8-16db4a8c8056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://training.openspan.com/product/beverages' and (text() = 'Beverages' or . = 'Beverages')]</value>
      <webElementGuid>b43f1cd1-be0e-43d3-8033-91a7aae09dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
