<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_sfirst_name</name>
   <tag></tag>
   <elementGuidId>f3a77fd2-6165-4ae9-a4e9-eab01607df1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sfirst_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sfirst_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b614bf0c-3b10-4ed5-ab03-62ac62e1b7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>e5a76156-1b7f-46d1-a05f-2c557b03a9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1241602-76c5-437c-aed1-a88020bda29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sfirst_name</value>
      <webElementGuid>5d6262e9-87a8-4deb-906e-d5efc549eff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(7);</value>
      <webElementGuid>30faad3a-96f7-4b75-8de8-57587841dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sfirst_name</value>
      <webElementGuid>0d2afc43-4e10-4476-adc1-7caf137ebf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>eab785db-b9f0-4bbc-a3db-9433c8ca0b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sfirst_name&quot;)</value>
      <webElementGuid>318955a7-70b4-4657-b662-27aff2f9d0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sfirst_name']</value>
      <webElementGuid>e4966af0-d124-412b-ba64-45f4b4538f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p/input</value>
      <webElementGuid>0492a74e-454a-4b3a-b088-2ec01c8652c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/input</value>
      <webElementGuid>0dc7f9fc-51a6-400b-9d9f-95e7ac52caae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sfirst_name' and @id = 'sfirst_name' and @placeholder = 'First Name']</value>
      <webElementGuid>c9bc68d5-5cec-4448-8e39-a6f06118b09b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
