<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_szip_code</name>
   <tag></tag>
   <elementGuidId>21446bbe-8df9-4871-8179-cfca8688840d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='szip_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#szip_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a15edf23-f51e-491e-bb62-91ac5179bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>03008b6e-bcf3-4cb8-a6d2-e9262bcbd7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5ef64ea-3cc7-49df-80be-362c12942ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>szip_code</value>
      <webElementGuid>6557e344-7dd4-4bca-b55e-9e72aaf61841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(12);</value>
      <webElementGuid>f6418423-edb0-447e-908f-7053a6c072b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>szip_code</value>
      <webElementGuid>348016bc-6b21-45fd-b01a-2f19c6e48145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP Code</value>
      <webElementGuid>dd97162b-54f0-4f4c-8845-3f666d795eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;szip_code&quot;)</value>
      <webElementGuid>733cbb74-ee19-45ae-b2aa-2b44f6179677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='szip_code']</value>
      <webElementGuid>581b3bcb-8e2e-493e-89dc-ad74330bf749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p[4]/input</value>
      <webElementGuid>eabadf12-44f5-47c6-af9a-e544e70a8065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[4]/input</value>
      <webElementGuid>ccb575e7-957d-4afd-b7b7-00b0cdd9a705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'szip_code' and @id = 'szip_code' and @placeholder = 'ZIP Code']</value>
      <webElementGuid>f47671ac-f22f-404a-8cc0-6802d390b07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
