<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify Credit Limit_submit</name>
   <tag></tag>
   <elementGuidId>e91a8cc7-9686-468c-a579-5c03f7a8274b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abbb5ec2-b324-427a-ae43-caf162e140f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dd25a7f7-4fa4-435e-ae88-60b7d0329da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7522c8cb-c9cd-4db3-be8f-afc661180932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit action-button</value>
      <webElementGuid>651def88-7941-4fff-9297-4331643ee04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_button</value>
      <webElementGuid>c48b8940-3a50-45c2-b84b-4e6377c09f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ce240e41-f877-4de0-9fda-521fe89b8edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>javascript:validate_fields_3();</value>
      <webElementGuid>e88fdac7-6def-4019-8b46-efa5157c1196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_button&quot;)</value>
      <webElementGuid>8ee38541-b323-42ff-99dc-1c7381b5bb33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit_button']</value>
      <webElementGuid>e14408c0-6d75-4b5b-a04d-0600228fd4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='progressbar_container']/fieldset[3]/input[2]</value>
      <webElementGuid>2da69a48-5e9b-4c2a-905f-a13d5e7bb992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/input[2]</value>
      <webElementGuid>13b200a6-fe22-4b90-8654-eacfc8de7138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit' and @id = 'submit_button']</value>
      <webElementGuid>b00f2a4c-83b9-4fd4-baf8-1bb7f36cc8d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
