<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 3 Tell Us How You Will Pay_card_number</name>
   <tag></tag>
   <elementGuidId>f00c8b3a-66bb-48c5-94d8-02e6f2375d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4154812c-e4b6-4a28-a77e-8150bd41a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5970d56c-63c2-490f-bf28-e20dc7e08e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>a90021f8-0898-48f5-a11a-8a7664328e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>7775968a-7d4f-4614-9b1a-3bdfa45dbd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>aeb9c132-d848-4063-8fbf-085ce8dbc13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field_3(2);</value>
      <webElementGuid>ca66bf22-1738-4071-bff7-cce37191a973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatory</value>
      <webElementGuid>e8ebd2a6-94d6-4d7d-97b5-375fef332002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number&quot;)</value>
      <webElementGuid>cea15b6b-4fca-4ca1-9bb7-d9e3e644fb21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number']</value>
      <webElementGuid>00594a22-dd47-4540-a077-6c98909c34c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit_card_content']/p[2]/input</value>
      <webElementGuid>d5d3be36-f341-4ce6-9de3-16a91a0d300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[2]/input</value>
      <webElementGuid>b4308f09-c34f-4a5c-9d08-a115744843a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'card_number' and @id = 'card_number' and @placeholder = 'Card Number']</value>
      <webElementGuid>f7a1bcd7-452d-4122-a859-c569a36314f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
