<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_bzip_code</name>
   <tag></tag>
   <elementGuidId>d592884d-7991-4e7a-8327-fac2fc8719ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bzip_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bzip_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e452b22d-9769-4130-baf3-b0e6ef9a848a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>33b0a803-488c-4210-a6ec-d47134caf3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aebcaa27-f07c-4645-b21f-cb51094f35d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bzip_code</value>
      <webElementGuid>98df480d-0bf6-421e-8b89-400dc2241fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(6);</value>
      <webElementGuid>ab51ae1f-e1aa-442f-a861-b1b72bc3ed94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bzip_code</value>
      <webElementGuid>f1c00b74-d2e9-42ae-82ab-570858dc697b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP Code</value>
      <webElementGuid>002c8bc8-55ac-4c3e-ba45-cfdd32b08898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bzip_code&quot;)</value>
      <webElementGuid>4d344a46-4465-4579-8b4b-44c020255f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bzip_code']</value>
      <webElementGuid>127a282d-81e7-4dcd-a747-bc30607443a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing_section']/p[4]/input</value>
      <webElementGuid>d4635e59-23ee-4a43-91b5-e5652a317886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>e26b810d-4698-49ab-9036-45662740c2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bzip_code' and @id = 'bzip_code' and @placeholder = 'ZIP Code']</value>
      <webElementGuid>eb4c9ede-72cd-471a-affd-22b385e06398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
