<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 3 Tell Us How You Will Pay_security_code</name>
   <tag></tag>
   <elementGuidId>4feec1dc-7e44-4622-a3c4-58d9d12917a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='security_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#security_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfa91308-44ac-4c83-bf13-2d577ad9463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c30cbb50-697b-4ff8-b47c-9e80c73c8f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>security_code</value>
      <webElementGuid>7a7522d2-18c5-4a08-adef-ede293a3ed1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>security_code</value>
      <webElementGuid>88a7d210-496f-4c0b-b595-6c852193cf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Security Code</value>
      <webElementGuid>959bbd43-604b-4096-8853-a8ffe19bc176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field_3(1);</value>
      <webElementGuid>a4dc92a1-1190-4b31-8eab-efe83192a66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatory</value>
      <webElementGuid>f23d028a-ee93-49ba-bc4d-89f3f04a387b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;security_code&quot;)</value>
      <webElementGuid>998b7eeb-2cac-4c78-b517-5a056ba62ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='security_code']</value>
      <webElementGuid>14108a5b-bed9-4259-bb77-9b2bcdf08ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit_card_content']/p/input</value>
      <webElementGuid>a42c906d-11f7-4917-ac04-ec1dae0c7cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p/input</value>
      <webElementGuid>db17a215-88ab-4d45-8b84-fb5552301bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'security_code' and @id = 'security_code' and @placeholder = 'Security Code']</value>
      <webElementGuid>4166c834-e9f6-4e72-8e20-eb7302fa0b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
