<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Notifications_next</name>
   <tag></tag>
   <elementGuidId>bc5426a0-4b8f-4670-a8b3-ec371d722e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next2_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#next2_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8d7e554-24b8-4852-8fd4-af4c7ebefc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8769f55c-2dd2-4d74-a3c6-2509e3c19d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>b28ababa-cb01-46cf-870d-1d563b77a8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next action-button</value>
      <webElementGuid>d77b51b9-d4f3-45e9-9c68-8161e80baea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>a12a0436-f9fb-4567-a60f-8577c9f46158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next2_button</value>
      <webElementGuid>68b75044-fb0d-4860-9ff4-692a752642a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>javascript:validate_fields();</value>
      <webElementGuid>4a910d28-cbec-4527-a03f-19d76058a9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next2_button&quot;)</value>
      <webElementGuid>cff9ec4f-0103-48a5-9971-16e852378d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next2_button']</value>
      <webElementGuid>5e70ae0f-b7c2-428b-9ba4-c6be63623ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='progressbar_container']/fieldset[2]/input[2]</value>
      <webElementGuid>ffdfcb61-fb14-43f1-8018-2b62d548c577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input[2]</value>
      <webElementGuid>71458ad5-a651-497d-a230-45f7b0e9b0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'next' and @id = 'next2_button']</value>
      <webElementGuid>89ce9c36-31a6-40fb-9519-3885612014f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
