<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_bprimary_phone</name>
   <tag></tag>
   <elementGuidId>f4cfca27-61bf-41c9-8371-718738107daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bprimary_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bprimary_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f58c062-f495-4c37-9d46-938421074439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size mandatory</value>
      <webElementGuid>93748922-c79a-4490-995f-1fb0c82e4852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61c7317d-4f2f-4cc7-843b-ef217de36747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bprimary_phone</value>
      <webElementGuid>acb511f3-4cd4-4a11-ac58-9f84a689639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(4);</value>
      <webElementGuid>efde119f-4d01-4261-af96-1708cbcd2b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bprimary_phone</value>
      <webElementGuid>0d9d6874-f81b-4158-b509-b1f8b46e8983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Primary Phone</value>
      <webElementGuid>d301c6b2-df1b-44ce-9705-8fea19ff49b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bprimary_phone&quot;)</value>
      <webElementGuid>2e4e1b1b-e6da-4acb-b700-88cba1c96424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bprimary_phone']</value>
      <webElementGuid>fa1eda27-0b30-423d-abdd-bd688393c3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing_section']/p[5]/input[2]</value>
      <webElementGuid>afc1162a-cbfc-46a1-86d6-fe097ba902ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input[2]</value>
      <webElementGuid>877b314a-e86f-4c98-8de3-345900c7be9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bprimary_phone' and @id = 'bprimary_phone' and @placeholder = 'Primary Phone']</value>
      <webElementGuid>4084f0bc-9163-430c-b7a1-2cd286a8a608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
