<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_scompany_name</name>
   <tag></tag>
   <elementGuidId>22e76e55-d583-403c-910f-5c86cc226f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scompany_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#scompany_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb52857f-5f29-4b74-805f-3f8e0035e455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94eabb71-9777-43f4-bb72-a259f32d9a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scompany_name</value>
      <webElementGuid>8fd733d9-7c59-4d90-8dbe-e13c79bd507f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scompany_name</value>
      <webElementGuid>8db28c90-b0b1-4423-89a4-5211f4da1b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_long_size</value>
      <webElementGuid>e546ffc4-2b6d-4fb6-a32a-2f4da535e533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name (Optional)</value>
      <webElementGuid>45ae6b05-eded-4a33-8e8a-6ecf1bd22a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scompany_name&quot;)</value>
      <webElementGuid>8e955b27-74f0-4cc5-9182-39d213255d30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='scompany_name']</value>
      <webElementGuid>9f54beed-bee8-42fc-ab05-31d3453cf18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p[2]/input</value>
      <webElementGuid>e4ba5300-f070-41cf-bd4a-3e82b2e0ea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]/input</value>
      <webElementGuid>6d4c6458-346f-46b9-a49a-d885f9b3817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'scompany_name' and @id = 'scompany_name' and @placeholder = 'Company Name (Optional)']</value>
      <webElementGuid>5ee81a1c-6d66-4d71-842f-db016d8f38a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
