<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_slast_name</name>
   <tag></tag>
   <elementGuidId>19f20e83-dfac-452e-a8c9-452f8584074c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slast_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slast_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8500f0b-06c0-46c6-b67c-c09264273660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>a579a449-934d-49e8-9928-626775733f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>926389a6-4522-4000-93d0-ac9116dcf17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slast_name</value>
      <webElementGuid>d32df64e-3d4a-4b3d-b76b-802ef91f8faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(8);</value>
      <webElementGuid>c67c3a63-fb2a-4803-9871-24e9fb75ac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slast_name</value>
      <webElementGuid>27f4fceb-7002-43f9-b954-71f8533ecd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>b1b0e04c-2e62-4c05-ace8-a3e7ea9f5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slast_name&quot;)</value>
      <webElementGuid>a7dadc4e-0742-44d8-9b0f-8a5e591032b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slast_name']</value>
      <webElementGuid>2b5df1f9-84fc-4c22-8084-ddd05045c4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p/input[2]</value>
      <webElementGuid>041e541f-62f5-404b-b46c-ef27577c3b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/input[2]</value>
      <webElementGuid>c55719d7-c412-4061-b512-7c2488d288c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'slast_name' and @id = 'slast_name' and @placeholder = 'Last Name']</value>
      <webElementGuid>29b6fffc-d02d-47d2-b4c9-0668d08ef287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
