<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_bcompany_name</name>
   <tag></tag>
   <elementGuidId>ebbd814e-95be-4d2a-91c4-a1fec3c3e34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bcompany_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bcompany_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0775c807-b24e-414f-ba7d-31eb7caba06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1faa060-b852-4ba8-83e3-c7d841c39370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bcompany_name</value>
      <webElementGuid>e3f0f183-b3b9-44c8-9e09-f96400b036be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bcompany_name</value>
      <webElementGuid>ba47cf89-7515-42fc-9341-74ebf0dea909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_long_size</value>
      <webElementGuid>a37b5fd3-9085-4b1e-b23f-c3cd687b681a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name (Optional)</value>
      <webElementGuid>e492886d-9450-40b7-b498-7f2ede5787b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bcompany_name&quot;)</value>
      <webElementGuid>b651fb32-846e-4eda-8e62-3645734a70c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bcompany_name']</value>
      <webElementGuid>bf2f39cd-a9f4-43fa-9436-8f94617cd0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing_section']/p[2]/input</value>
      <webElementGuid>7187fc9c-8dab-43f5-a31e-1e8ad878bdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>1074840c-639b-4897-8bcf-e6b94500e72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bcompany_name' and @id = 'bcompany_name' and @placeholder = 'Company Name (Optional)']</value>
      <webElementGuid>a547dd37-b0a7-46e7-a1ea-d337c3adfdc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
