<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_barea_code</name>
   <tag></tag>
   <elementGuidId>91c0ce9d-f010-47cd-baa6-e1faccdf75fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='barea_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#barea_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>107205b8-7086-48c3-92e1-deadffba452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>fccab157-636f-401d-8e48-dd68e2debcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75a4ad10-81a5-4044-932a-4c0ab2aa470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>barea_code</value>
      <webElementGuid>c629c843-fcf7-4933-8e46-a010f44a498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(3);</value>
      <webElementGuid>1deeb20b-eb83-4594-ac38-8f78b605becc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>barea_code</value>
      <webElementGuid>16529a88-8f66-4fee-8e50-cfa71c42f652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Area Code</value>
      <webElementGuid>8542f6da-5304-467e-8a21-92fafc5735ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barea_code&quot;)</value>
      <webElementGuid>909bcb32-1956-462b-aa2c-35723264ab13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='barea_code']</value>
      <webElementGuid>2738e9be-2455-479f-8959-1c6c359ab648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing_section']/p[5]/input</value>
      <webElementGuid>6d96dc3d-bc6c-4d64-8e3e-5cc1adda6ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>f425a4c8-8b6b-4ec5-9c4b-ddfd88f79c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'barea_code' and @id = 'barea_code' and @placeholder = 'Area Code']</value>
      <webElementGuid>37b268bf-7f6c-4489-8bdf-145d9fe5e364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
