<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_bfirst_name</name>
   <tag></tag>
   <elementGuidId>12f30efb-d092-4f30-8e98-20e920edb6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bfirst_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bfirst_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>688c7165-5476-48e6-b5cb-7328f36d3000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_middle_size</value>
      <webElementGuid>235cad44-e067-4099-9a02-b65cfadc0cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c23c38c5-5fcd-4c3a-9ed2-1da35cc8fbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bfirst_name</value>
      <webElementGuid>4fef59cb-8fda-42e8-b38c-44a488120a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(1);</value>
      <webElementGuid>4bcf4f88-197c-4bc8-9fe5-f20a7c3fb058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bfirst_name</value>
      <webElementGuid>f8748481-b95a-496c-8ec0-3a4354572dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>8e999506-f023-4487-b3b7-f7d77cc9f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bfirst_name&quot;)</value>
      <webElementGuid>80bacb64-0519-4eaf-9478-0bb8ea490104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bfirst_name']</value>
      <webElementGuid>388144ff-3fc6-4692-9d0f-2ececf37c285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing_section']/p/input</value>
      <webElementGuid>256bbe6a-7c92-487e-a380-05c9f1b33a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>c2dff040-ef60-4b20-8e57-42516b83bf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bfirst_name' and @id = 'bfirst_name' and @placeholder = 'First Name']</value>
      <webElementGuid>e8ea6043-fb06-493c-9ccf-12d56656b8d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
