<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Notifications_email_address</name>
   <tag></tag>
   <elementGuidId>e27342bd-4282-4649-8b8a-c056416b9ace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email_address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3072978e-adf9-4cdc-b7d8-9c102b7adda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f49a4ca7-6a23-4902-b8c8-1e0866fa6c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_address</value>
      <webElementGuid>90915de2-7254-48a8-97c5-e18e2e3e2c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_long_size</value>
      <webElementGuid>234b5bb1-e9ca-4086-b679-f08f8a45932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address (Optional)</value>
      <webElementGuid>16568d43-c071-4e27-a24a-bc8a6de7cebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_section&quot;)/p[5]/input[@class=&quot;input_long_size&quot;]</value>
      <webElementGuid>88a143ab-8a12-491b-b981-de20994c4303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email_address']</value>
      <webElementGuid>8331487a-e20d-4bd0-9810-696795be1387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p[5]/input</value>
      <webElementGuid>75e33e74-8f97-4a6f-9218-e9e1da84efdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[5]/input</value>
      <webElementGuid>6220d72e-c445-49ff-80e5-eb8817eee3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_address' and @placeholder = 'Email Address (Optional)']</value>
      <webElementGuid>271a3406-5905-4ce7-b9fb-846d197b9595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
