<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_sstreet_address</name>
   <tag></tag>
   <elementGuidId>6bb36984-f623-4305-838a-be1dc7157d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sstreet_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sstreet_address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3ac936c-3474-4102-ba13-733078e7d9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da9055b7-a7ae-4940-9fdd-4916085052e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sstreet_address</value>
      <webElementGuid>7e3f7374-67a2-4af3-8b77-953bf9bc6339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field(11);</value>
      <webElementGuid>ca1acf71-5201-4731-8b98-82bad3845718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sstreet_address</value>
      <webElementGuid>76f98851-9823-4482-abc3-283ebb5a6c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>dd8a6351-49f1-48a6-8fe1-2f9363339d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_long_size</value>
      <webElementGuid>d7d50916-c139-4e40-8fd5-adc325584f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sstreet_address&quot;)</value>
      <webElementGuid>b66fcab3-6f98-4d4c-876f-95497f2930c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sstreet_address']</value>
      <webElementGuid>f460ff4e-49ae-433f-9e4d-ce57082b5e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_section']/p[3]/input</value>
      <webElementGuid>6102c245-2e5e-43f7-bedb-9b8f93a83b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[3]/input</value>
      <webElementGuid>6d9519b0-f56b-4c2d-9358-df80c972ca1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sstreet_address' and @id = 'sstreet_address' and @placeholder = 'Street Address']</value>
      <webElementGuid>bd3554d6-768b-485f-852c-6a7ce28fd8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
