<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Expiration Year2014201520162017201820192020</name>
   <tag></tag>
   <elementGuidId>66c62fa8-6c51-4360-8633-5338b646bf8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expiry_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry_year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4c1754f5-1d83-472f-a547-d347787ac705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry_year</value>
      <webElementGuid>95702fc4-a4e2-4808-aff2-841d5a626526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry_year</value>
      <webElementGuid>469dd9ba-12af-4d32-8d68-f2b329cf5386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_middle_size mandatory</value>
      <webElementGuid>9db54faf-1b99-40a2-9cc9-da80c0616066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field_3(5);</value>
      <webElementGuid>c7e7fa96-b8f6-459a-8311-7cf48d21ef22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Expiration Year
2014
2015
2016
2017
2018
2019
2020
</value>
      <webElementGuid>37df87d5-8a00-40a4-b066-d79e17ea09c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry_year&quot;)</value>
      <webElementGuid>054c7a72-a0a0-4fb2-a077-61333e5e3e69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expiry_year']</value>
      <webElementGuid>933dc4da-6316-4952-bf64-59ae87e1ebeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit_card_content']/p[3]/select[2]</value>
      <webElementGuid>3d945b2b-08f2-483d-9156-448ea91df597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3 Tell Us How You Will Pay'])[1]/following::select[3]</value>
      <webElementGuid>eab13fab-af49-4877-8e0f-bca72c679df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important: Do not enter real credit card information on this training web page.'])[1]/following::select[3]</value>
      <webElementGuid>e9ae921a-45d4-4ae5-b548-a85576396567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify Credit Limit'])[1]/preceding::select[1]</value>
      <webElementGuid>1b27f2f6-8c6f-4c01-8563-23d6633e3a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert'])[1]/preceding::select[1]</value>
      <webElementGuid>69380c7c-87d1-4870-97f2-27ecb18936ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>40a7037f-f733-4f6b-916a-8e88c5323be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expiry_year' and @name = 'expiry_year' and (text() = '
Expiration Year
2014
2015
2016
2017
2018
2019
2020
' or . = '
Expiration Year
2014
2015
2016
2017
2018
2019
2020
')]</value>
      <webElementGuid>fae8f22d-4978-4a4f-9a70-1c111b9c6105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
