<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Expiration MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember</name>
   <tag></tag>
   <elementGuidId>0c95fd53-226e-49d4-9315-477ad812a5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expiry_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f358c0a6-ae44-4dff-84bb-e2198a03ca62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry_month</value>
      <webElementGuid>2937c8e5-b545-40e9-a746-2dab39729fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry_month</value>
      <webElementGuid>555d76d0-c10e-4912-bfaa-00ef9cf3a663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_middle_size mandatory</value>
      <webElementGuid>1b4a205c-11a6-4e70-9050-96bdbfa36a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:validate_field_3(4);</value>
      <webElementGuid>d899525b-6903-4b56-a392-c6428c52f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Expiration Month
January
February
March
April
May
June
July
August
September
October
November
December
</value>
      <webElementGuid>821b06ea-1223-4bbc-9ea8-5ca9cc89d68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry_month&quot;)</value>
      <webElementGuid>1f9e45bf-2f1b-4a42-a1d2-d368b68fc53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expiry_month']</value>
      <webElementGuid>ffcc21a3-2cab-4d13-807b-4eb1643c39d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit_card_content']/p[3]/select</value>
      <webElementGuid>4cd786fd-611b-49ba-bb7e-692002cbd055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3 Tell Us How You Will Pay'])[1]/following::select[2]</value>
      <webElementGuid>0be3b1eb-ef85-41cd-84c0-27ce3b192acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important: Do not enter real credit card information on this training web page.'])[1]/following::select[2]</value>
      <webElementGuid>79a52058-d94b-4a69-919d-0a3058819641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify Credit Limit'])[1]/preceding::select[2]</value>
      <webElementGuid>5dad17a8-fa5a-4ab5-9e5e-780d0d7362f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert'])[1]/preceding::select[2]</value>
      <webElementGuid>1d3533eb-a05d-4d0d-b54e-c2f47c4f06a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/select</value>
      <webElementGuid>a162b5da-0288-4342-8de5-89af81a50a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expiry_month' and @name = 'expiry_month' and (text() = '
Expiration Month
January
February
March
April
May
June
July
August
September
October
November
December
' or . = '
Expiration Month
January
February
March
April
May
June
July
August
September
October
November
December
')]</value>
      <webElementGuid>4a1c04ec-979c-46be-8d0d-819e044c87ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
