<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a password of at least 4 characters_user_pass</name>
   <tag></tag>
   <elementGuidId>4f88adc7-949f-4095-bf92-a38852d778fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_pass']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_pass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>719d6c94-a041-49cb-aec7-7dfb4add09f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_text</value>
      <webElementGuid>496eccd3-3383-4084-9338-2b55910108c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pass</value>
      <webElementGuid>ba505e6b-faee-48c4-80c9-9e27649ca2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_pass</value>
      <webElementGuid>840fd367-66c0-4e6b-9f2a-45d2b5f5ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2d6fe39a-46c0-4176-ae05-96bfb2a9eb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>bd3198bc-aaa8-4ae9-bd73-26cffbff4242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>deba407d-f6ce-4f70-a5ba-acc45584c94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_pass&quot;)</value>
      <webElementGuid>e7f69983-29fb-4ad9-9b0b-916b44242151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_pass']</value>
      <webElementGuid>885aaf67-e8a4-4031-8132-83c2f5e412c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='login_section']/tbody/tr[2]/td/input</value>
      <webElementGuid>b0769762-a80e-4401-9e80-8d389052d119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>10ca8391-f625-4091-98f7-1f6f4b0212f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'user_pass' and @id = 'user_pass' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>9dfcc00e-f731-4da4-b91a-51cfecd0ba8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
